language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker-compose --version
  - docker version
install:
- docker-compose build
notifications:
  email:
    on_success: never
    on_failure: always