language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker-compose --version
  - docker version
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker-compose build
script:
  - docker push henrygustavo/shopping_cart_identity
  - docker push henrygustavo/shopping_cart_cartbasket
notifications:
  email:
    on_success: never
    on_failure: always