version: "3.2"

networks:
  backend:


services:
  cartworker:
    image: henrygustavo/shopping_cart_order
    build: 
      context: ./cart.worker
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: cartworker
    ports:
      - "9004:80"
    networks:
      - backend

  product:
    image: henrygustavo/shopping_cart_product
    build: 
      context: ./product
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: productapi
    ports:
      - "9003:80"
    networks:
      - backend

  cart:
    image: henrygustavo/shopping_cart_cartbasket
    build: 
      context: ./cart
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: cartapi
    ports:
      - "9002:80"
    networks:
      - backend

  identity:
    image: henrygustavo/shopping_cart_identity
    build: 
      context: ./identity
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: identityapi
    ports:
      - "9001:80"
    networks:
      - backend

  gateway:
    image: henrygustavo/shopping_cart_gateway
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
    container_name: gatewayapi
    ports:
      - "9000:80"
    networks:
      - backend